name: koalition
markdown: kramdown
exclude: ['node_modules', 'gulpfile.js', 'package.json']

title: Koalition gegen antimuslimischen Rassismus
email: 
description: > # this means to ignore newlines until "baseurl:"
  Willkommen auf der offiziellen Seite der Koalition gegen antimuslimischen Rassismus.
  Welcome to the official website of the Coalition against anti-muslim racism.

baseurl: '/koalition' # ''

future: true
# index:
#   de:
#   en: /en/

date-style:
  - language: de
    format: '%d-%m-%Y'
  - language: en
    format: '%Y-%m-%d'

read-more:
  - language: de
    phrase: 'Details anzeigen'
  - language: en
    phrase: 'Show details'

nav:
  # de
  - language: de
    index:
    links:
      - ref: about
        title: Über uns
        href: about

      - ref: phenomenon
        title: Phänomen
        href: phenomenon

      - ref: partners
        title: Partner*innen
        href: partners

      - ref: supporters
        title: Unterstützende
        href: supporters

      - ref: contact
        title: Kontakt
        href: contact

      - ref: socialmedia
        title: Social Media
        href: socialmedia

      - ref: links
        title: Links & Literatur
        href: links

      # - ref: news
      #   title: Aktuelles
      #   href: news

  # en
  - language: en
    index: en
    links:
      - ref: about
        title: About us
        href: about

      - ref: phenomenon
        title: Phenomenon
        href: phenomenon

      - ref: partners
        title: Partners
        href: partners

      - ref: supporters
        title: Supporters
        href: supporters

      - ref: contact
        title: Contact
        href: contact

      - ref: links
        title: Links & Literature
        href: links

tabs: 
  - language: de
    links:
    - ref: "dokustelle"
      title: Dokustelle
      initClass: "showFeedContainer"
      socialmedia:
        - type: twitter
          href: https://twitter.com/dokustelle?ref_src=twsrc%5Etfw
        - type: facebook
          href: href=https%3A%2F%2Fwww.facebook.com%2FDokustelleOesterreich%2F
    - ref: "zara"
      title: ZARA - Zivilcourage & Anti-Rassismus-Arbeit
      socialmedia:
        - type: twitter
          href: https://twitter.com/Verein_ZARA?ref_src=twsrc%5Etfw
        - type: facebook
          href: href=https%3A%2F%2Fwww.facebook.com%2Fzara.or.at%2F