name: koalition
markdown: kramdown
exclude: ['node_modules', 'gulpfile.js', 'package.json']

title: Koalition gegen antimuslimischen Rassismus
email: 
description: > # this means to ignore newlines until "baseurl:"
  Willkommen auf der offiziellen Seite der Koalition gegen antimuslimischen Rassismus.
  Welcome to the official website of the Coalition against anti-muslim racism.

baseurl: '/koalition' # ''

future: true
# index:
#   de:
#   en: /en/

date-style:
  - language: de
    format: '%d-%m-%Y'
  - language: en
    format: '%Y-%m-%d'

read-more:
  - language: de
    phrase: 'Details anzeigen'
  - language: en
    phrase: 'Show details'

nav:
  # de
  - language: de
    index:
    links:
      - ref: about
        title: Über uns
        href: about

      - ref: phenomenon
        title: Phänomen
        href: phenomenon

      - ref: partners
        title: Partner*innen
        href: partners

      - ref: contact
        title: Kontakt
        href: contact

      - ref: links
        title: Links & Literatur
        href: links

      # - ref: news
      #   title: Aktuelles
      #   href: news


  # en
  - language: en
    index: en
    links:
      - ref: about
        title: About us
        href: about

      - ref: phenomenon
        title: Phenomenon
        href: phenomenon

      - ref: partners
        title: Partners
        href: partners

      - ref: contact
        title: Contact
        href: contact

      - ref: links
        title: Links & Literature
        href: links

      # - ref: news
      #   title: News
      #   href: news
  # en:
  #  about:
  #   title: About us
  #   href: about_us
  #  projects:
  #   title: Projects
  #   href: projects
